---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  playbook: test/integration/default.yml
  hosts: all
  require_ansible_omnibus: true
  require_chef_for_busser: false
  require_ruby_for_busser: false

platforms:
  - name: debian/jessie64
  - name: ubuntu/trusty64

suites:
  - name: default

verifier:
  name: inspec
