---
- name: Copy Filebeat config file.
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    mode: "0644"
    owner: root
    group: root
    validate: "/usr/bin/filebeat -configtest -c %s"
  notify: restart filebeat

- name: Enable Filebeat service.
  service:
    name: filebeat
    state: running
    enabled: yes
