---
- name: Copy logstash-forwarder config file.
  template:
    src: logstash-forwarder.conf
    dest: /etc/logstash-forwarder.conf
    mode: "0644"
    owner: root
    group: root
  notify: restart logstash-forwarder

  # The logstash-forwarder process needs group membership in "adm"
  # in order to read log files under Debian (e.g. syslog).
- name: Edit config to add logstash user to adm group.
  lineinfile:
    dest: /etc/default/logstash-forwarder
    regexp: '^group='
    line: 'group="adm"'
    state: present
  notify: restart logstash-forwarder

