---
- include: packages.yml

- include: ssl_keys.yml
  when: logstash_client_ssl_certificate != ""

- include: filebeat.yml
  when: "'filebeat' in logstash_client_beats_packages"

- include: topbeat.yml
  when: "'topbeat' in logstash_client_beats_packages"
