---
- name: Add ElasticSearch apt key.
  become: yes
  apt_key:
    url: https://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: Add Beats apt repository.
  become: yes
  apt_repository:
    repo: "deb http://packages.elastic.co/beats/apt stable main"
    state: present

- name: Install beat packages.
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: beats_packages
