---
- name: Add ElasticSearch apt key.
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

- name: Install beats pre-req software
  apt:
    name: "{{ item }}"
  with_items: "{{ beats_client_beats_prereq }}"

- name: Add Beats apt repository.
  apt_repository:
    repo: "{{ beats_client_elastic_repo_url }}"
    state: present

- name: Install beat packages.
  apt:
    name: "{{ item }}={{ beats_client_version }}"
    state: present
  with_items: "{{ beats_client_beats_packages }}"

- name: Configure service files.
  lineinfile:
    path: "/lib/systemd/system/{{ item }}.service"
    insertafter: "\\[Service\\]"
    line: "EnvironmentFile=-{{ beats_client_environment_dir }}/{{ item }}"
  with_items: "{{ beats_client_beats_packages }}"

- name: Create environment files
  copy:
    content: ""
    dest: "{{ beats_client_environment_dir }}/{{ item }}"
    force: no
  with_items: "{{ beats_client_beats_packages }}"

- name: Reload systemd
  systemd:
    daemon_reload: yes
