---
- name: Add ElasticSearch apt key.
  become: yes
  apt_key:
    url: https://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: Add logstash-forwarder apt repository.
  become: yes
  apt_repository:
    repo: 'deb http://packages.elasticsearch.org/logstashforwarder/debian stable main'
    state: present
  register: apt_repo_config

- name: Update apt cache.
  become: yes
  apt:
    update_cache: yes
  when: apt_repo_config.changed

- name: Install logstash-forwarder.
  become: yes
  apt:
    name: logstash-forwarder
    state: present
