---
- name: Add ElasticSearch apt key.
  apt_key:
    id: "{{ logstash_elastic_pgp_key }}"
    keyserver: pgp.mit.edu
    state: present

- name: Install beats pre-req software
  apt:
    name: "{{ item }}"
  with_items: "{{ logstash_client_beats_prereq }}"

- name: Add Beats apt repository.
  apt_repository:
    repo: "{{ logstash_elastic_repo_url }}"
    state: present

- name: Install beat packages.
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ logstash_client_beats_packages }}"
