---
- name: add elasticsearch apt key
  apt_key:
    url: https://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state: present

- name: add logstash-forwarder apt repo
  apt_repository:
    repo: 'deb http://packages.elasticsearch.org/logstashforwarder/debian stable main'
    state: present
  register: apt_repo_config

- name: update apt cache
  apt:
    update_cache: yes
  when: apt_repo_config.changed

- name: install logstash-forwarder
  apt:
    name: logstash-forwarder
    state: present
