---
- name: Add ElasticSearch apt key.
  shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
#  apt_key:
#    id: "{{ beats_client_elastic_pgp_key }}"
#    keyserver: "{{ beats_client_keyserver }}"
#    state: present

- name: Install beats pre-req software
  apt:
    name: "{{ item }}"
  with_items: "{{ beats_client_beats_prereq }}"

- name: Add Beats apt repository.
  apt_repository:
    repo: "{{ beats_client_elastic_repo_url }}"
    state: present

- name: Install beat packages.
  apt:
    name: "{{ item }}={{ beats_client_version }}"
    state: present
  with_items: "{{ beats_client_beats_packages }}"
