---
# tasks file for logstash-client
- name: Create SSL certificate directory.
  become: yes
  file:
    path: "{{ logstash_client_ssl_certificate_base_directory }}"
    mode: "0755"
    owner: root
    group: root
    state: directory

- name: Copy logstash-forwarder SSL certificate.
  become: yes
  copy:
    src: "{{ logstash_client_ssl_certificate }}"
    dest: "{{ logstash_client_ssl_certificate_base_directory }}/{{ logstash_client_ssl_certificate | basename }}"
    mode: "0644"
    owner: root
    group: root
  notify:
    - update ca certificates
    - restart filebeat

