---
# handlers file for logstash-client
- name: restart filebeat
  become: yes
  service:
    name: filebeat
    state: restarted

- name: restart topbeat
  become: yes
  service:
    name: topbeat
    state: restarted
