---
- name: restart filebeat
  become: yes
  service:
    name: filebeat
    state: restarted

- name: restart packetbeat
  become: yes
  service:
    name: packetbeat
    state: restarted

- name: restart topbeat
  become: yes
  service:
    name: topbeat
    state: restarted

- name: restart heartbeat
  become: yes
  service:
    name: heartbeat
    state: restarted

- name: restart heartbeat-elastic
  become: yes
  service:
    name: heartbeat-elastic
    state: restarted

- name: restart metricbeat
  become: yes
  service:
    name: metricbeat
    state: restarted
