---
# handlers file for logstash-client
- name: restart logstash-forwarder
  become: yes
  service:
    name: logstash-forwarder
    state: restarted

- name: update ca certificates
  become: yes
  command: update-ca-certificates -f

- name: restart filebeat
  become: yes
  service:
    name: filebeat
    state: restarted

- name: restart topbeat
  become: yes
  service:
    name: topbeat
    state: restarted
